#!/usr/bin/env python3
"""
Safely inserts 30 Elevé templates into templates.ts
Finds the closing ] and inserts before it.
"""
import sys
import os

project = sys.argv[1]
templates_file = os.path.join(project, 'src/lib/templates.ts')

# Read current file
with open(templates_file, 'r') as f:
    content = f.read()

# Check not already patched
if 'sound-stillness-session' in content:
    print("Already patched — skipping")
    sys.exit(0)

# The new templates to insert
new_templates = r"""
  // ══════════════════════════════════════════════════════════════════════════
  //  SECTION C — Elevé 11C–11E Curated Templates (seed Claude generation)
  //  30 templates across 8 categories. No plan field = Claude generates.
  // ══════════════════════════════════════════════════════════════════════════

  // ── WELLNESS ──────────────────────────────────────────────────────────────

  {
    id: 'sound-stillness-session', label: 'Sound & Stillness Session',
    tagline: 'An hour of sound. A week of clarity.',
    description: 'A guided sound bath and breathwork experience for residents seeking restoration.',
    category: 'wellness', atmosphere: 'wellness-focused',
    demographic: ['Young professionals (25–35)', 'Mature residents (50+)'],
    idealSeasons: ['Spring', 'Fall / Autumn'], budgetTier: 'accessible',
    tags: ['no-alcohol', 'low-staffing', 'morning'],
    venue: 'Indoor', alcohol: 'No alcohol',
    staffingComplexity: 'light', operationalDifficulty: 1, setupTimeHours: 1,
    cleanupComplexity: 'minimal',
    vendorTypes: ['Sound bath practitioner', 'Wellness catering'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'Mist space with eucalyptus before guests arrive. Herbal tea and cucumber water at close. Lavender sachet take-home elevates recall.',
    residentExperienceNotes: 'The silence itself is the amenity — protect it operationally. Start and end on time.',
    setupNotes: 'Darken room entirely. Radial mat layout. One blanket and eye pillow per mat. Quiet-entry sign 15 min before start.',
    staffingNotes: '1 building staff for check-in. 1 sound bath practitioner. Minimize presence during session.',
    enhancements: ['Add a certified breathwork facilitator', 'Partner with local apothecary for take-home kit', 'Offer post-session one-on-one booking'],
    flyerHeadline: 'An hour of sound. A week of clarity.',
    emailIntro: "We're setting aside an hour this season for something different — a guided sound bath and breathwork session designed to help you reset, right here in the building.",
    previewTags: ['Morning', 'Indoor', 'Non-Alcoholic'],
    formData: { eventType: 'Wellness & Yoga Morning', budget: '$1,000 \u2013 $2,500', attendance: '20 \u2013 40 residents', season: 'Spring', venue: 'Indoor', alcohol: 'No alcohol', demographic: 'Young professionals (25\u201335)', notes: 'Sound bath practitioner with crystal bowls. Guided breathwork opening. Yoga mats, eye pillows, lavender-infused towels. Dim lighting essential. Close with herbal tea.' },
  },

  {
    id: 'rooftop-yoga-at-dawn', label: 'Rooftop Yoga at Dawn',
    tagline: 'Sunrise practice. Rooftop. Yours.',
    description: 'An early morning yoga practice on the rooftop terrace as the city wakes up.',
    category: 'wellness', atmosphere: 'wellness-focused',
    demographic: ['Young professionals (25–35)', 'Mixed demographic'],
    idealSeasons: ['Spring', 'Summer'], budgetTier: 'accessible',
    tags: ['no-alcohol', 'outdoor', 'morning', 'rooftop'],
    venue: 'Indoor & Outdoor', alcohol: 'No alcohol',
    staffingComplexity: 'light', operationalDifficulty: 1, setupTimeHours: 1,
    cleanupComplexity: 'minimal',
    vendorTypes: ['Yoga instructor', 'Light catering (juice, cold brew, fruit)'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'Cold-pressed juice in glass bottles. The city view at dawn is the hero — do not over-decorate. Rolled towels at each mat signal boutique hotel.',
    residentExperienceNotes: 'Early start (6:30–7:30 AM) serves working professionals. The rooftop exclusivity creates a "this building is different" feeling.',
    setupNotes: 'Confirm rooftop access 48 hours ahead. Mats facing east or toward best view. Refreshment station at rooftop entry. Weather backup room confirmed.',
    staffingNotes: '1 yoga instructor (all-levels certified). 1 building team member for access and mat setup.',
    enhancements: ['Partner with local cold brew brand for sponsored refreshments', 'Offer post-practice 15-min guided meditation', 'Make it a monthly series'],
    flyerHeadline: 'Sunrise practice. Rooftop. Yours.',
    emailIntro: "This month, we're opening the rooftop early — just for you. An all-levels yoga practice as the city wakes up, followed by cold-pressed juice and coffee.",
    previewTags: ['Morning', 'Rooftop', 'Non-Alcoholic'],
    formData: { eventType: 'Wellness & Yoga Morning', budget: '$1,000 \u2013 $2,500', attendance: '20 \u2013 40 residents', season: 'Summer', venue: 'Indoor & Outdoor', alcohol: 'No alcohol', demographic: 'Young professionals (25\u201335)', notes: 'Sunrise rooftop yoga. All levels. Mats provided. Cold brew, pressed juice, and light fruit after practice.' },
  },

  {
    id: 'early-morning-restore', label: 'Early Morning Restore',
    tagline: 'Move gently. Leave restored.',
    description: 'A slow-flow movement and guided stretch class designed for stress recovery.',
    category: 'wellness', atmosphere: 'wellness-focused',
    demographic: ['Mature residents (50+)', 'Mixed demographic'],
    idealSeasons: ['Fall / Autumn', 'Winter'], budgetTier: 'accessible',
    tags: ['no-alcohol', 'low-staffing', 'morning', 'all-abilities'],
    venue: 'Indoor', alcohol: 'No alcohol',
    staffingComplexity: 'light', operationalDifficulty: 1, setupTimeHours: 1,
    cleanupComplexity: 'minimal',
    vendorTypes: ['Restorative yoga instructor', 'Herbal tea catering'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'Herbal tea in proper mugs, not paper cups. Soft blankets — cheap fleece signals the wrong tier. Handwritten note at each mat is a small premium touch.',
    residentExperienceNotes: 'This demographic responds to being cared for — not challenged. The gentleness is the amenity.',
    setupNotes: 'Extra space between mats. Bolsters, blocks, blankets at every mat. Room temperature 72–74°F. Soft ambient lighting only.',
    staffingNotes: '1 restorative instructor experienced with older adults. 1 building team member for mat setup.',
    enhancements: ['Add post-class 10-min guided relaxation with warm eye pillows', 'Partner with local herbal tea brand for take-home selection', 'Offer a 4-week Restore Series'],
    flyerHeadline: 'Move gently. Leave restored.',
    emailIntro: "We're hosting a gentle morning movement class this month — designed for residents who want to move, stretch, and restore without intensity. All levels, all abilities.",
    previewTags: ['Morning', 'Indoor', 'All Abilities'],
    formData: { eventType: 'Wellness & Yoga Morning', budget: '$1,000 \u2013 $2,500', attendance: '20 \u2013 40 residents', season: 'Fall / Autumn', venue: 'Indoor', alcohol: 'No alcohol', demographic: 'Mature residents (50+)', notes: 'Slow-flow restorative movement. Low intensity, all abilities. Blankets and bolsters provided. End with herbal tea.' },
  },

  {
    id: 'private-spa-morning', label: 'Private Spa Morning',
    tagline: 'The spa is coming to you. Book your slot.',
    description: "A curated morning of licensed wellness treatments brought into the building's amenity space.",
    category: 'wellness', atmosphere: 'wellness-focused',
    demographic: ['Mature residents (50+)', 'Mixed demographic', 'Young professionals (25–35)'],
    idealSeasons: ['Winter', 'Fall / Autumn'], budgetTier: 'mid',
    tags: ['no-alcohol', 'appointment-based', 'premium-feel'],
    venue: 'Indoor', alcohol: 'No alcohol',
    staffingComplexity: 'moderate', operationalDifficulty: 2, setupTimeHours: 1,
    cleanupComplexity: 'moderate',
    vendorTypes: ['Mobile spa vendor (licensed therapists)', 'Wellness catering'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'Licensed professionals only — non-negotiable. The appointment format creates the spa experience. Small take-home extends the feeling.',
    residentExperienceNotes: 'Spa access in a residential building is a genuine amenity differentiator. Appeals to residents who value self-care but lack time.',
    setupNotes: 'Treatment stations partitioned for privacy. Appointment booking 1 week in advance — 20-minute slots. Confirm all therapists licensed and insured.',
    staffingNotes: '3–4 licensed therapists. 1 building staff for appointment management. Send confirmations 24 hours before each slot.',
    enhancements: ['Partner with premium skincare brand for take-home samples', 'Add guided meditation for residents waiting', 'Make it quarterly'],
    flyerHeadline: 'The spa is coming to you. Book your slot.',
    emailIntro: "This month we're bringing the spa to the building — massage, facials, and restorative treatments, right here. Appointments are 20 minutes. Book before they're gone.",
    previewTags: ['Morning', 'Indoor', 'By Appointment'],
    formData: { eventType: 'Wellness & Yoga Morning', budget: '$2,500 \u2013 $5,000', attendance: '20 \u2013 40 residents', season: 'Winter', venue: 'Indoor', alcohol: 'No alcohol', demographic: 'Mixed demographic', notes: 'Mobile spa pop-up. 3–4 treatment stations: massage, facials, hand treatments. Residents book 20-minute slots in advance. Herbal tea and infused water throughout.' },
  },

  // ── CULINARY ──────────────────────────────────────────────────────────────

  {
    id: 'sommelier-social', label: 'Sommelier Social',
    tagline: 'Four wines. One evening. A lot to discover.',
    description: 'A guided wine tasting led by a sommelier, paired with artisan boards and resident conversation.',
    category: 'culinary', atmosphere: 'upscale-social',
    demographic: ['Young professionals (25–35)', 'Mature residents (50+)', 'Mixed demographic'],
    idealSeasons: ['Fall / Autumn', 'Winter'], budgetTier: 'mid',
    tags: ['full-bar', 'seated', 'educational', 'wine'],
    venue: 'Indoor', alcohol: 'Full bar',
    staffingComplexity: 'moderate', operationalDifficulty: 2, setupTimeHours: 2,
    cleanupComplexity: 'moderate',
    vendorTypes: ['Certified sommelier', 'Artisan charcuterie and cheese vendor', 'Wine supplier'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'Proper Riedel-style stems. Printed tasting cards with wine notes. Boards generous. Low candlelight transforms the room for under $20.',
    residentExperienceNotes: 'Residents leave feeling educated, not sold to. The conversation between residents is the real product.',
    setupNotes: 'Round or cluster table format. Stems at every seat before guests arrive. Tasting mats with wine list printed. Boards as centerpieces.',
    staffingNotes: '1 certified sommelier. 1 building event staff for check-in. 1 server for board replenishment.',
    enhancements: ['Add a mystery wine revealed at the end', 'Source wines from a single acclaimed region', 'Partner with local wine shop for post-event purchase'],
    flyerHeadline: 'Four wines. One evening. A lot to discover.',
    emailIntro: "We're inviting you to an evening with a certified sommelier — a guided tasting of four wines paired with artisan boards, right here in the building.",
    previewTags: ['Evening', 'Full Bar', 'Educational'],
    formData: { eventType: 'Wine & Cheese Evening', budget: '$2,500 \u2013 $5,000', attendance: '30 \u2013 60 residents', season: 'Fall / Autumn', venue: 'Indoor', alcohol: 'Full bar', demographic: 'Young professionals (25\u201335)', notes: 'Guided wine tasting with certified sommelier. 4–5 wines across two regions. Artisan cheese boards, charcuterie, seasonal accompaniments. Intimate round-table format.' },
  },

  {
    id: 'chefs-counter-evening', label: "Chef's Counter Evening",
    tagline: 'Twenty seats. One chef. An evening worth reserving.',
    description: 'An intimate chef-led tasting dinner where residents gather around the kitchen counter.',
    category: 'culinary', atmosphere: 'upscale-social',
    demographic: ['Mature residents (50+)', 'Young professionals (25–35)'],
    idealSeasons: ['Fall / Autumn', 'Winter'], budgetTier: 'premium',
    tags: ['full-bar', 'seated', 'limited-seats', 'chef-led'],
    venue: 'Indoor', alcohol: 'Full bar',
    staffingComplexity: 'intensive', operationalDifficulty: 4, setupTimeHours: 3,
    cleanupComplexity: 'involved',
    vendorTypes: ['Private chef (4+ years fine dining)', 'Wine pairing sommelier', 'Event rental'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: "The chef's narrative is the luxury. Printed menus with chef name and course descriptions. One unexpected element per course creates lasting recall.",
    residentExperienceNotes: 'The exclusivity of 20 seats is the amenity. Residents who attend once will request it annually.',
    setupNotes: 'Counter or U-shaped seating essential. Chef requires 2-hour kitchen setup window. Confirm all equipment in advance.',
    staffingNotes: '1 private chef. 1 sommelier. 1 building event staff. Kitchen assistant behind the scenes.',
    enhancements: ['Feature a guest chef from a recognized local restaurant', 'Wine pairing card as take-home keepsake', "Offer a chef's table waiting list"],
    flyerHeadline: 'Twenty seats. One chef. An evening worth reserving.',
    emailIntro: "We're opening the kitchen this month for a very limited evening — a private chef's counter dinner for twenty residents. Four courses, wine pairings.",
    previewTags: ['Evening', 'Full Bar', 'Limited Seats'],
    formData: { eventType: 'Cooking Class', budget: '$5,000 \u2013 $10,000', attendance: '20 \u2013 40 residents', season: 'Winter', venue: 'Indoor', alcohol: 'Full bar', demographic: 'Mature residents (50+)', notes: "Intimate chef's counter format. Up to 20 residents. 4–5 courses explaining technique and sourcing. Wine pairings included." },
  },

  {
    id: 'garden-harvest-table', label: 'Garden Harvest Table',
    tagline: 'One long table. One season. The whole building.',
    description: 'A seasonal communal dining experience built around local farmers market sourcing.',
    category: 'culinary', atmosphere: 'relaxed-luxury',
    demographic: ['Mixed demographic', 'Young professionals (25–35)', 'Mixed ages, family-oriented'],
    idealSeasons: ['Fall / Autumn', 'Summer'], budgetTier: 'mid',
    tags: ['wine-beer', 'communal', 'farm-to-table', 'seasonal'],
    venue: 'Indoor & Outdoor', alcohol: 'Wine & beer only',
    staffingComplexity: 'moderate', operationalDifficulty: 3, setupTimeHours: 2,
    cleanupComplexity: 'moderate',
    vendorTypes: ['Farm-to-table caterer', 'Local wine and craft beer vendor', 'Floral vendor'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'The sourcing story is the luxury — name the farms. Abundance reads premium: generous platters refilled without asking. Natural materials only.',
    residentExperienceNotes: 'Communal seating forces conversation — residents meet neighbors. Works for a broad demographic range.',
    setupNotes: 'Long communal table — non-negotiable. Natural linen runners. Low seasonal florals. Pillar candles. Family-style service platters.',
    staffingNotes: '1 caterer who can narrate sourcing. 2 servers for 40–60 guests. 1 building staff.',
    enhancements: ['Partner with local farm for named sourcing credit', 'Add seasonal cocktail on arrival', 'Small take-home — seasonal jam or honey'],
    flyerHeadline: 'One long table. One season. The whole building.',
    emailIntro: "This season, we're gathering around a long harvest table — a family-style dinner built entirely from locally sourced, seasonal ingredients.",
    previewTags: ['Evening', 'Wine & Beer', 'Communal'],
    formData: { eventType: 'Brunch Gathering', budget: '$2,500 \u2013 $5,000', attendance: '30 \u2013 60 residents', season: 'Fall / Autumn', venue: 'Indoor & Outdoor', alcohol: 'Wine & beer only', demographic: 'Mixed demographic', notes: 'Long communal table dinner with seasonal locally sourced produce. Natural linen, simple florals, candles. Wine and craft beer.' },
  },

  {
    id: 'reserve-cellar-tasting', label: 'Reserve Cellar Tasting',
    tagline: "Wines you won't find. An evening you won't forget.",
    description: "A focused tasting of allocated and small-production wines with a guided collector's narrative.",
    category: 'culinary', atmosphere: 'upscale-social',
    demographic: ['Mature residents (50+)', 'Young professionals (25–35)'],
    idealSeasons: ['Fall / Autumn', 'Winter'], budgetTier: 'premium',
    tags: ['full-bar', 'seated', 'collector', 'limited-seats'],
    venue: 'Indoor', alcohol: 'Full bar',
    staffingComplexity: 'moderate', operationalDifficulty: 2, setupTimeHours: 2,
    cleanupComplexity: 'moderate',
    vendorTypes: ['Master sommelier or wine director', 'Specialty wine importer', 'Artisan food pairing caterer'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'The wines themselves are the luxury — source genuinely allocated bottles. Printed tasting notes designed with care. Silence during commentary is a luxury.',
    residentExperienceNotes: 'Appeals strongly to residents who already know wine. The rarity of the bottles is a talking point beyond the evening.',
    setupNotes: 'Two stems per person minimum. Formal tasting notes at each seat. Decant reds 30–60 minutes before service.',
    staffingNotes: '1 master sommelier. 1 trained server for pour service. 1 building staff.',
    enhancements: ['Source one truly rare bottle as centerpiece', 'Commission custom printed tasting booklet', 'Add blind tasting round for final wine'],
    flyerHeadline: "Wines you won't find. An evening you won't forget.",
    emailIntro: "We've sourced something special — a private tasting of allocated and small-production wines led by a master sommelier. Space is limited to twenty residents.",
    previewTags: ['Evening', 'Full Bar', 'Collector'],
    formData: { eventType: 'Wine & Cheese Evening', budget: '$5,000 \u2013 $10,000', attendance: '20 \u2013 40 residents', season: 'Winter', venue: 'Indoor', alcohol: 'Full bar', demographic: 'Mature residents (50+)', notes: 'High-end wine tasting with allocated or library wines. Master sommelier. 5–6 wines, formal tasting notes, pairing bites. 20 residents max.' },
  },

  {
    id: 'craft-cocktail-brunch', label: 'Craft Cocktail Brunch',
    tagline: 'Weekend. Brunch. Craft cocktails. Yours.',
    description: "A weekend brunch elevated with a craft cocktail bar, a chef's spread, and a relaxed social format.",
    category: 'culinary', atmosphere: 'relaxed-luxury',
    demographic: ['Young professionals (25–35)', 'Mixed demographic'],
    idealSeasons: ['Spring', 'Summer'], budgetTier: 'mid',
    tags: ['full-bar', 'weekend', 'social', 'brunch'],
    venue: 'Indoor & Outdoor', alcohol: 'Full bar',
    staffingComplexity: 'moderate', operationalDifficulty: 2, setupTimeHours: 2,
    cleanupComplexity: 'moderate',
    vendorTypes: ['Brunch caterer with live egg station', 'Craft cocktail bartender'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'Premium juice for mimosas (fresh-pressed, not carton). Smoked salmon signals premium. Linen napkins, not paper.',
    residentExperienceNotes: 'Weekend timing serves residents with long weekday hours. Most likely to become a recurring resident request.',
    setupNotes: 'Live egg station is the anchor — position as visible focal point. Craft cocktail bar at entrance. Buffet by category: savory, smoked, pastry, fruit.',
    staffingNotes: '1 craft bartender. 1 chef for live egg station. 1–2 servers. 1 building staff.',
    enhancements: ['Add bottomless mimosas with 90-minute window', 'Partner with local bakery for featured pastry', 'Bring in a jazz duo for a 90-minute live set'],
    flyerHeadline: 'Weekend. Brunch. Craft cocktails. Yours.',
    emailIntro: "We're doing brunch properly this month — a chef's spread, a craft cocktail bar, and a few hours to slow down with your neighbors. No reservations. Just show up between 11 and 2.",
    previewTags: ['Weekend', 'Full Bar', 'Social'],
    formData: { eventType: 'Brunch Gathering', budget: '$2,500 \u2013 $5,000', attendance: '30 \u2013 60 residents', season: 'Spring', venue: 'Indoor & Outdoor', alcohol: 'Full bar', demographic: 'Young professionals (25\u201335)', notes: 'Weekend brunch. Craft cocktail bar — Bloody Marys, spritzes, mimosas with premium juice. Chef spread: eggs station, smoked salmon, pastries, seasonal fruit. 11 AM–2 PM.' },
  },

  {
    id: 'bourbon-and-provisions', label: 'Bourbon & Provisions',
    tagline: 'Four bourbons. Serious provisions. One evening.',
    description: 'An intimate bourbon tasting paired with artisan provisions — charcuterie, aged cheese, and smoked goods.',
    category: 'culinary', atmosphere: 'upscale-social',
    demographic: ['Mature residents (50+)', 'Young professionals (25–35)'],
    idealSeasons: ['Fall / Autumn', 'Winter'], budgetTier: 'mid',
    tags: ['full-bar', 'seated', 'spirits', 'intimate'],
    venue: 'Indoor', alcohol: 'Full bar',
    staffingComplexity: 'light', operationalDifficulty: 1, setupTimeHours: 1,
    cleanupComplexity: 'minimal',
    vendorTypes: ['Spirits specialist or bourbon brand ambassador', 'Artisan charcuterie and cheese vendor'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'Proper Glencairn glasses signal a serious tasting. The provisions pairing narrative elevates the experience. Warm amber lighting only.',
    residentExperienceNotes: 'Appeals to residents who collect or follow American whiskey. Intimate headcount ensures genuine conversation.',
    setupNotes: 'Glencairn or rocks glasses pre-set. Provisions boards as generous centerpieces. Water and plain crackers for palate cleansing.',
    staffingNotes: '1 spirits specialist. 1 building staff for arrivals and provisions management.',
    enhancements: ['Feature one allocated bourbon as paid-upgrade final pour', 'Add cigar option if outdoor space available', 'Partner with local distillery'],
    flyerHeadline: 'Four bourbons. Serious provisions. One evening.',
    emailIntro: "We're gathering this month for a guided bourbon tasting paired with artisan charcuterie, aged cheese, and smoked provisions. Space limited to thirty residents.",
    previewTags: ['Evening', 'Full Bar', 'Intimate'],
    formData: { eventType: 'Bourbon & Cigar Evening', budget: '$2,500 \u2013 $5,000', attendance: '20 \u2013 40 residents', season: 'Fall / Autumn', venue: 'Indoor', alcohol: 'Full bar', demographic: 'Mature residents (50+)', notes: 'Guided bourbon tasting — 4–5 expressions across mash bills and age statements. Artisan charcuterie, aged cheeses, smoked nuts, dark chocolate. Spirits specialist. Intimate seated format.' },
  },

  // ── SOCIAL / ROOFTOP ──────────────────────────────────────────────────────

  {
    id: 'golden-hour-reception', label: 'Golden Hour Reception',
    tagline: 'The rooftop. The skyline. The moment.',
    description: 'An elegant rooftop cocktail reception timed to sunset, with passed appetisers and a full bar.',
    category: 'social', atmosphere: 'upscale-social',
    demographic: ['Young professionals (25–35)', 'Mixed demographic'],
    idealSeasons: ['Summer', 'Spring'], budgetTier: 'premium',
    tags: ['full-bar', 'rooftop', 'outdoor', 'instagram-worthy'],
    venue: 'Indoor & Outdoor', alcohol: 'Full bar',
    staffingComplexity: 'intensive', operationalDifficulty: 4, setupTimeHours: 3,
    cleanupComplexity: 'involved',
    vendorTypes: ['Craft cocktail bar vendor', 'Passed canapé caterer', 'DJ or ambient music', 'Event rental'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'Signature cocktail names tied to the building. The golden hour itself is the luxury — do not let late setup compete with it.',
    residentExperienceNotes: 'The view at golden hour is a built-in Instagram moment. This event converts hesitant residents into building advocates.',
    setupNotes: 'Check sunset time and schedule start 90 minutes before. String lighting installed the morning of. Lounge clusters, not rows. Weather contingency essential.',
    staffingNotes: '2 bartenders minimum for 60+ guests. 2–3 servers for passed canapés. 1 building event lead. 1 door staff for first 45 minutes.',
    enhancements: ['Create signature cocktail named after the building', 'Hire saxophonist or acoustic guitarist for first hour', 'Commission local photographer for 2 hours'],
    flyerHeadline: 'The rooftop. The skyline. The moment.',
    emailIntro: "We're opening the rooftop this month for golden hour — cocktails, canapés, and a view worth seeing. Join your neighbors for an evening that starts at sunset.",
    previewTags: ['Rooftop', 'Full Bar', 'Summer'],
    formData: { eventType: 'Cocktail Reception', budget: '$5,000 \u2013 $10,000', attendance: '50 \u2013 100 residents', season: 'Summer', venue: 'Indoor & Outdoor', alcohol: 'Full bar', demographic: 'Young professionals (25\u201335)', notes: 'Rooftop cocktail reception starting 90 minutes before sunset. Passed canapés. Full craft cocktail bar with 2–3 signature drinks plus wine and beer. Ambient music. Smart casual.' },
  },

  {
    id: 'terrace-aperitivo-social', label: 'Terrace Aperitivo Social',
    tagline: 'Aperitivo hour. Your terrace. This month.',
    description: 'A relaxed Italian-style aperitivo hour with spritz cocktails, antipasti, and resident conversation.',
    category: 'social', atmosphere: 'relaxed-luxury',
    demographic: ['Mixed demographic', 'Young professionals (25–35)', 'Mature residents (50+)'],
    idealSeasons: ['Spring', 'Summer'], budgetTier: 'mid',
    tags: ['wine-beer', 'outdoor', 'relaxed', 'european'],
    venue: 'Indoor & Outdoor', alcohol: 'Wine & beer only',
    staffingComplexity: 'moderate', operationalDifficulty: 1, setupTimeHours: 1,
    cleanupComplexity: 'minimal',
    vendorTypes: ['Aperitivo bar vendor or caterer', 'Italian antipasti vendor or deli'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'Quality Prosecco and properly made spritzes. Oranges and grapefruit as garnishes signal effort. The European format creates sophistication without formality.',
    residentExperienceNotes: 'Works exceptionally well for mixed demographics. Early timing means residents do not commit their whole evening.',
    setupNotes: 'Casual furniture — bistro tables, lounge pieces. Antipasti on large boards. Bar staffed, not self-serve. Pre-batch spritzes for speed.',
    staffingNotes: '1–2 bartenders. 1 server for antipasti replenishment. 1 building staff.',
    enhancements: ['Feature local Italian deli for antipasti sourcing', 'Make it recurring — "First Thursday Aperitivo"', 'Bring in local gelato vendor for dessert close'],
    flyerHeadline: 'Aperitivo hour. Your terrace. This month.',
    emailIntro: "We're keeping it simple this month — spritz cocktails, antipasti, and good company on the terrace. Drop by when you're ready and stay as long as you like.",
    previewTags: ['Terrace', 'Wine & Beer', 'Relaxed'],
    formData: { eventType: 'Cocktail Reception', budget: '$2,500 \u2013 $5,000', attendance: '30 \u2013 60 residents', season: 'Spring', venue: 'Indoor & Outdoor', alcohol: 'Wine & beer only', demographic: 'Mixed demographic', notes: 'Italian aperitivo format. Aperol spritz, Campari soda, Prosecco, non-alcoholic option. Antipasti: olives, cured meats, giardiniera, bruschetta. Early evening 5:30–7:30 PM.' },
  },

  {
    id: 'midnight-cocktail-service', label: 'Midnight Cocktail Service',
    tagline: 'After hours. An evening worth staying up for.',
    description: 'A late-night intimate cocktail experience for residents who prefer the quieter hours.',
    category: 'social', atmosphere: 'upscale-social',
    demographic: ['Young professionals (25–35)'],
    idealSeasons: ['Winter', 'Fall / Autumn'], budgetTier: 'mid',
    tags: ['full-bar', 'late-night', 'intimate', 'moody'],
    venue: 'Indoor', alcohol: 'Full bar',
    staffingComplexity: 'moderate', operationalDifficulty: 2, setupTimeHours: 1,
    cleanupComplexity: 'minimal',
    vendorTypes: ['Craft cocktail bartender', 'Small bites caterer'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'The cocktail menu should have names. A printed cocktail card signals everything. Darkness and quiet are the luxury — protect both.',
    residentExperienceNotes: 'Late-night formats serve a resident segment daytime events miss. The intimacy creates a members-club feeling.',
    setupNotes: 'Dim all overheads, candles and accent lighting only. Curated playlist pre-set. Small bites on slate or wood boards. Room set before 8:30 PM.',
    staffingNotes: '1 skilled craft bartender as the centerpiece. 1 staff for check-in and bites.',
    enhancements: ['Commission building-named cocktails from the bartender', 'Add vinyl record player with curated selection', 'Partner with local chocolatier for pairings'],
    flyerHeadline: 'After hours. Your building. An evening worth staying up for.',
    emailIntro: "We're doing something different this month — a late-night cocktail service in the lounge, starting at 9. A craft bartender, four signature drinks. RSVP required.",
    previewTags: ['Late Evening', 'Full Bar', 'Intimate'],
    formData: { eventType: 'Cocktail Reception', budget: '$2,500 \u2013 $5,000', attendance: '20 \u2013 40 residents', season: 'Winter', venue: 'Indoor', alcohol: 'Full bar', demographic: 'Young professionals (25\u201335)', notes: 'Late evening cocktail service 9 PM–midnight. 3–4 signature craft cocktails. Small bites — charcuterie, chocolate, savory pastry. Low lighting, curated playlist.' },
  },

  {
    id: 'rooftop-cinema-evening', label: 'Rooftop Cinema Evening',
    tagline: 'Rooftop. Film. Craft cocktails. Dusk.',
    description: 'A curated film screening on the rooftop with craft cocktails and premium concessions.',
    category: 'social', atmosphere: 'relaxed-luxury',
    demographic: ['Young professionals (25–35)', 'Mixed demographic'],
    idealSeasons: ['Summer', 'Spring'], budgetTier: 'mid',
    tags: ['full-bar', 'rooftop', 'outdoor', 'film'],
    venue: 'Indoor & Outdoor', alcohol: 'Full bar',
    staffingComplexity: 'moderate', operationalDifficulty: 3, setupTimeHours: 3,
    cleanupComplexity: 'moderate',
    vendorTypes: ['Outdoor cinema rental', 'Craft cocktail bartender', 'Premium concessions caterer'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'Film curation signals someone considered the audience. Pre-packed concession boxes eliminate service noise during film. Lounge seating with blankets creates boutique hotel feeling.',
    residentExperienceNotes: 'The rooftop setting makes this feel like a private screening. Film selection by resident poll creates pre-event engagement.',
    setupNotes: 'Screen orientation for minimal light interference at dusk. Bar away from screen. Lounge clusters — not rows. Blankets one per seat. Concession boxes pre-packed at arrival.',
    staffingNotes: '1 AV technician. 1 craft bartender (bar closes at film start). 1 building staff.',
    enhancements: ['Partner with local cinema for curation credibility', 'Create signature cocktail themed to the film', 'Offer post-film discussion'],
    flyerHeadline: 'Rooftop. Film. Craft cocktails. Dusk.',
    emailIntro: "We're screening a film on the rooftop this month — craft cocktails before the film, premium concessions, and the city behind the screen. Show up at dusk.",
    previewTags: ['Rooftop', 'Full Bar', 'Film'],
    formData: { eventType: 'Movie Night', budget: '$2,500 \u2013 $5,000', attendance: '30 \u2013 60 residents', season: 'Summer', venue: 'Indoor & Outdoor', alcohol: 'Full bar', demographic: 'Young professionals (25\u201335)', notes: 'Rooftop film screening for adults. Craft cocktail bar. Curated film. Premium concessions: flavored popcorn, charcuterie boxes, sparkling water. Lounge seating. Start at dusk.' },
  },

  {
    id: 'the-rooftop-residency', label: 'The Rooftop Residency',
    tagline: 'The Rooftop Residency. Edition [N]. This Month.',
    description: "A recurring rooftop social series — the building's signature warm-season gathering.",
    category: 'social', atmosphere: 'upscale-social',
    demographic: ['Young professionals (25–35)', 'Mixed demographic'],
    idealSeasons: ['Spring', 'Summer'], budgetTier: 'mid',
    tags: ['full-bar', 'rooftop', 'recurring', 'signature'],
    venue: 'Indoor & Outdoor', alcohol: 'Full bar',
    staffingComplexity: 'moderate', operationalDifficulty: 3, setupTimeHours: 2,
    cleanupComplexity: 'moderate',
    vendorTypes: ['Craft cocktail bartender', 'Rotating food vendor', 'Ambient music'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'The series format is itself the luxury signal. Edition numbering creates collector psychology. A consistent signature cocktail becomes a building trademark.',
    residentExperienceNotes: 'Recurring events build community more than one-off events. Residents who miss an edition feel FOMO.',
    setupNotes: 'Consistent setup every edition — same layout, same bar position. Rotate food concept each edition. Edition number printed on a card at the bar.',
    staffingNotes: '2 bartenders. 1–2 food vendor staff. 1 building event lead — same person each edition.',
    enhancements: ['Create a printed "Residency Passport" card for each edition', 'Feature different local food vendor each edition', 'At Edition 6 or 12, host a "Residency Anniversary"'],
    flyerHeadline: 'The Rooftop Residency. Edition [N]. This Month.',
    emailIntro: 'The Rooftop Residency is back for Edition [N] — this time featuring [food concept] and [music]. Same rooftop, same craft bar, something different every time.',
    previewTags: ['Rooftop', 'Full Bar', 'Recurring'],
    formData: { eventType: 'Rooftop Social', budget: '$2,500 \u2013 $5,000', attendance: '50 \u2013 100 residents', season: 'Summer', venue: 'Indoor & Outdoor', alcohol: 'Full bar', demographic: 'Young professionals (25\u201335)', notes: 'Monthly rooftop social during warm months. Consistent format: craft bar, rotating food concept, ambient music. The "Residency" name signals a series, not a one-off.' },
  },

  // ── NETWORKING ────────────────────────────────────────────────────────────

  {
    id: 'the-founders-collective', label: 'The Founders Collective',
    tagline: "The building's founders, in one room.",
    description: 'A structured professional social for resident entrepreneurs, founders, and executives.',
    category: 'networking', atmosphere: 'networking-focused',
    demographic: ['Young professionals (25–35)', 'Mature residents (50+)'],
    idealSeasons: ['Fall / Autumn', 'Winter'], budgetTier: 'mid',
    tags: ['full-bar', 'standing', 'structured', 'professional'],
    venue: 'Indoor', alcohol: 'Full bar',
    staffingComplexity: 'moderate', operationalDifficulty: 2, setupTimeHours: 1,
    cleanupComplexity: 'minimal',
    vendorTypes: ['Craft cocktail bartender', 'Elevated small bites caterer'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'The curation of who is in the room is the luxury — communicate selective invite. Conversation-starter cards prevent awkward silences.',
    residentExperienceNotes: 'Residents leave with at least one meaningful connection. Positions the building as a community of accomplished people.',
    setupNotes: 'Standing format with high-top tables. Slightly under-furnished so people circulate. Conversation starter card at each high-top.',
    staffingNotes: '1 skilled bartender. 1–2 servers for passed small bites. 1 building staff as active host and MC.',
    enhancements: ['Feature one resident as 5-minute spotlight speaker', 'Create private building Slack or LinkedIn group', 'Bring in photographer for headshots'],
    flyerHeadline: "The building's founders, in one room.",
    emailIntro: "We're bringing together the entrepreneurs, executives, and founders in the building for an evening of real conversation. RSVP required — space is intentionally curated.",
    previewTags: ['Evening', 'Full Bar', 'Professional'],
    formData: { eventType: 'Networking Mixer', budget: '$2,500 \u2013 $5,000', attendance: '30 \u2013 60 residents', season: 'Fall / Autumn', venue: 'Indoor', alcohol: 'Full bar', demographic: 'Young professionals (25\u201335)', notes: 'Professional networking for founders and executives. Structured conversation activations. Featured resident "60-second intro" format. Craft cocktails and elevated small bites.' },
  },

  {
    id: 'industry-salon', label: 'Industry Salon',
    tagline: 'One topic. One evening. Actual conversation.',
    description: 'A themed professional conversation evening built around a single industry or topic.',
    category: 'networking', atmosphere: 'networking-focused',
    demographic: ['Young professionals (25–35)', 'Mature residents (50+)'],
    idealSeasons: ['Winter', 'Fall / Autumn'], budgetTier: 'accessible',
    tags: ['wine-beer', 'intimate', 'speaker', 'intellectual'],
    venue: 'Indoor', alcohol: 'Wine & beer only',
    staffingComplexity: 'light', operationalDifficulty: 1, setupTimeHours: 1,
    cleanupComplexity: 'minimal',
    vendorTypes: ['Wine and beer vendor', 'Light snacks caterer'],
    requiresExternalVendor: false,
    luxuryPresentationNotes: 'The quality of the speaker and topic is the entire value proposition. A printed evening agenda card signals intentionality on a small budget.',
    residentExperienceNotes: 'Residents leave having learned something — the rarest outcome of a building event. Attracts residents who skip social events.',
    setupNotes: 'Semicircle or living-room seating — not classroom rows. Wine and beer self-serve. Max 35 people.',
    staffingNotes: '1 building staff as host and conversation facilitator. Self-serve beverage format.',
    enhancements: ['Record speaker segment and share with absent residents', 'Create themed reading list', 'Make it a quarterly series'],
    flyerHeadline: 'One topic. One evening. Actual conversation.',
    emailIntro: "This month we're hosting an Industry Salon — an intimate evening built around [topic]. One featured voice, open discussion. Wine and light bites. Space is limited.",
    previewTags: ['Evening', 'Wine & Beer', 'Intellectual'],
    formData: { eventType: 'Networking Mixer', budget: '$1,000 \u2013 $2,500', attendance: '20 \u2013 40 residents', season: 'Winter', venue: 'Indoor', alcohol: 'Wine & beer only', demographic: 'Young professionals (25\u201335)', notes: 'Salon-style conversation evening. One featured resident or external speaker for 15 minutes, then open discussion. Wine and beer, light snacks. Intimate headcount.' },
  },

  {
    id: 'open-exchange-forum', label: 'Open Exchange Forum',
    tagline: 'Good wine. Interesting neighbors. Early enough to still have dinner.',
    description: 'An unstructured professional social where the building itself is the shared context.',
    category: 'networking', atmosphere: 'networking-focused',
    demographic: ['Young professionals (25–35)', 'Mixed demographic', 'Mature residents (50+)'],
    idealSeasons: ['Spring', 'Fall / Autumn'], budgetTier: 'accessible',
    tags: ['wine-beer', 'low-staffing', 'relaxed', 'professional'],
    venue: 'Indoor', alcohol: 'Wine & beer only',
    staffingComplexity: 'light', operationalDifficulty: 1, setupTimeHours: 1,
    cleanupComplexity: 'minimal',
    vendorTypes: ['Wine and beer vendor', 'Light bites caterer'],
    requiresExternalVendor: false,
    luxuryPresentationNotes: "The host's active introduction-making is the luxury at this budget tier. Good glassware at self-serve elevates the format.",
    residentExperienceNotes: 'Early timing and low-pressure format converts non-attendees into first-timers.',
    setupNotes: 'Minimal setup. Wine and beer with proper glassware. Light bites throughout. No podium, no microphone. Early timing (5:30–7:30 PM).',
    staffingNotes: '1 building staff as active host. 1 staff for bites replenishment.',
    enhancements: ['Add resident directory card listing names and industries', 'Partner with local wine shop for curated selections', 'Make it a recurring quarterly touchpoint'],
    flyerHeadline: 'Good wine. Interesting neighbors. Early enough to still have dinner.',
    emailIntro: 'No agenda, no speaker, no structured anything — just an easy evening with the professionals who happen to live in this building. Drop by after work.',
    previewTags: ['Early Evening', 'Wine & Beer', 'Relaxed'],
    formData: { eventType: 'Networking Mixer', budget: '$1,000 \u2013 $2,500', attendance: '30 \u2013 60 residents', season: 'Spring', venue: 'Indoor', alcohol: 'Wine & beer only', demographic: 'Mixed demographic', notes: 'Low-structure professional social for all resident professionals. No speaker, no agenda. Good wine, light food. Early evening timing for busy schedules.' },
  },

  // ── WORKSHOP ──────────────────────────────────────────────────────────────

  {
    id: 'modern-needle-atelier', label: 'Modern Needle Atelier',
    tagline: 'Something made by hand. Something worth keeping.',
    description: 'A guided embroidery and needlework session with modern patterns and a social atmosphere.',
    category: 'workshop', atmosphere: 'relaxed-luxury',
    demographic: ['Young professionals (25–35)', 'Mixed demographic'],
    idealSeasons: ['Fall / Autumn', 'Winter'], budgetTier: 'accessible',
    tags: ['wine-beer', 'hands-on', 'take-home', 'craft'],
    venue: 'Indoor', alcohol: 'Wine & beer only',
    staffingComplexity: 'light', operationalDifficulty: 1, setupTimeHours: 1,
    cleanupComplexity: 'minimal',
    vendorTypes: ['Textile/embroidery instructor', 'Wine and beer vendor'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'Modern geometric patterns — not vintage florals. Quality thread in a curated color palette signals curation. Printed pattern card makes the take-home feel designed.',
    residentExperienceNotes: 'Residents leave with something handmade. The focused activity removes social pressure — ideal for residents who find pure mixers uncomfortable.',
    setupNotes: 'Each seat needs flat work surface. Pre-stage all materials: hoop, needle, thread, pattern card, scissors. Good overhead lighting essential.',
    staffingNotes: '1 textile instructor with contemporary teaching style. 1 building staff to manage arrivals.',
    enhancements: ['Commission custom Elevé-themed pattern', 'Partner with local textile studio', 'Create follow-up session for residents to finish work'],
    flyerHeadline: 'Something made by hand. Something worth keeping.',
    emailIntro: "We're hosting an embroidery evening this month — a guided session with a textile artist, modern patterns, and wine throughout. No experience needed. You'll take your work home.",
    previewTags: ['Evening', 'Wine & Beer', 'Take-Home'],
    formData: { eventType: 'Cooking Class', budget: '$1,000 \u2013 $2,500', attendance: '20 \u2013 40 residents', season: 'Winter', venue: 'Indoor', alcohol: 'Wine & beer only', demographic: 'Young professionals (25\u201335)', notes: 'Guided embroidery workshop. Contemporary geometric patterns. All materials provided. Wine and light snacks. Residents take work home.' },
  },

  {
    id: 'cocktail-craft-session', label: 'Cocktail Craft Session',
    tagline: 'Learn to make it. Then drink it.',
    description: 'A hands-on cocktail making class led by a craft bartender — technique, not just tasting.',
    category: 'workshop', atmosphere: 'relaxed-luxury',
    demographic: ['Young professionals (25–35)', 'Mixed demographic'],
    idealSeasons: ['Spring', 'Summer'], budgetTier: 'mid',
    tags: ['full-bar', 'hands-on', 'educational', 'social'],
    venue: 'Indoor', alcohol: 'Full bar',
    staffingComplexity: 'moderate', operationalDifficulty: 2, setupTimeHours: 1,
    cleanupComplexity: 'moderate',
    vendorTypes: ['Craft bartender or mixologist', 'Spirits and mixer vendor'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'Quality spirits (mid-shelf minimum). Proper bar tools at each station. Printed take-home recipe card is the keepsake.',
    residentExperienceNotes: 'Residents leave knowing how to make a cocktail properly — lasting value. High repeat-request rates.',
    setupNotes: 'Each resident needs a station: shaker, strainer, jigger, mixing glass, garnish. Spirits pre-measured. Bartender needs 60 minutes setup. Cap attendance at 30.',
    staffingNotes: '1 craft bartender as lead instructor. 1 assistant for ice and cleanup. 1 building staff.',
    enhancements: ['Feature spirit from local distillery', 'Add blind taste test to crown best cocktail', 'Create building cocktail recipe booklet after 3–4 sessions'],
    flyerHeadline: 'Learn to make it. Then drink it.',
    emailIntro: "We're bringing in a craft bartender this month for a proper cocktail making session — not just tasting, actually making. Recipe cards to take home.",
    previewTags: ['Evening', 'Full Bar', 'Hands-On'],
    formData: { eventType: 'Cooking Class', budget: '$2,500 \u2013 $5,000', attendance: '20 \u2013 40 residents', season: 'Spring', venue: 'Indoor', alcohol: 'Full bar', demographic: 'Young professionals (25\u201335)', notes: 'Cocktail making workshop. Each resident makes 2 drinks using proper technique. Focus on 2–3 classic cocktails and one seasonal variation. All spirits, mixers, tools provided.' },
  },

  {
    id: 'ceramic-studio-evening', label: 'Ceramic Studio Evening',
    tagline: 'Make something with your hands. Pick it up in two weeks.',
    description: 'A hand-building ceramics session where residents create a small piece to take home after firing.',
    category: 'workshop', atmosphere: 'relaxed-luxury',
    demographic: ['Young professionals (25–35)', 'Mixed demographic', 'Mature residents (50+)'],
    idealSeasons: ['Fall / Autumn', 'Winter'], budgetTier: 'mid',
    tags: ['wine-beer', 'hands-on', 'take-home', 'craft'],
    venue: 'Indoor', alcohol: 'Wine & beer only',
    staffingComplexity: 'moderate', operationalDifficulty: 2, setupTimeHours: 1,
    cleanupComplexity: 'moderate',
    vendorTypes: ['Ceramics instructor with kiln access', 'Wine and beer vendor'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'The 2-week return of fired pieces extends the experience. A card with the piece — "Made at [Building Name], [Date]" — is a premium touch.',
    residentExperienceNotes: 'The take-home is the marketing — residents display pieces and tell the story. Cross-demographic appeal.',
    setupNotes: 'Cover all tables with canvas drop cloths. Each station: clay, bowl of water, wooden tools, sponge. Instructor needs 45 minutes setup. Wine station separate from work area.',
    staffingNotes: '1 ceramics instructor experienced with group hand-building. 1 building staff for check-in and wine service.',
    enhancements: ['Partner with local ceramics studio for instructor and kiln', 'Offer glaze selection at follow-up pickup event', 'Make it an annual event tied to a season'],
    flyerHeadline: 'Make something with your hands. Pick it up in two weeks.',
    emailIntro: "We're setting up a ceramics studio in the building this month. A hand-building session — you'll create a small piece, we'll have it fired, and you'll pick it up two weeks later.",
    previewTags: ['Evening', 'Wine & Beer', 'Take-Home'],
    formData: { eventType: 'Cooking Class', budget: '$2,500 \u2013 $5,000', attendance: '20 \u2013 40 residents', season: 'Fall / Autumn', venue: 'Indoor', alcohol: 'Wine & beer only', demographic: 'Mixed demographic', notes: 'Hand-building ceramics workshop. No wheel. Each resident creates one small piece. Instructor fires pieces after session and returns within 2 weeks. Wine throughout.' },
  },

  // ── FAMILY ────────────────────────────────────────────────────────────────

  {
    id: 'garden-cinema-evening', label: 'Garden Cinema Evening',
    tagline: 'Film under the sky. You pick the movie.',
    description: 'An outdoor film screening with premium concessions and a relaxed lawn setup.',
    category: 'family', atmosphere: 'family-focused',
    demographic: ['Mixed ages, family-oriented', 'Mixed demographic'],
    idealSeasons: ['Summer', 'Spring'], budgetTier: 'mid',
    tags: ['no-alcohol', 'outdoor', 'all-ages', 'film'],
    venue: 'Indoor & Outdoor', alcohol: 'No alcohol',
    staffingComplexity: 'moderate', operationalDifficulty: 2, setupTimeHours: 3,
    cleanupComplexity: 'moderate',
    vendorTypes: ['Outdoor cinema rental', 'Premium concessions caterer'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'Premium concessions differentiate this from a generic movie night. Soft blankets available for lending. Printed film program card is a charming touch.',
    residentExperienceNotes: 'The resident poll creates buy-in before the event. Families with children will remember this as a building highlight.',
    setupNotes: 'Screen and projector setup requires 3+ hours. Blanket area closest to screen, chairs further back. Start at dusk. Test audio levels before residents arrive.',
    staffingNotes: '1 AV vendor for projection and sound. 1–2 building staff for setup and concessions.',
    enhancements: ['Add pre-film DJ set for 30-minute arrival window', 'Partner with local ice cream truck for dessert close', 'Make it an annual summer series'],
    flyerHeadline: 'Film under the sky. You pick the movie.',
    emailIntro: "We're setting up an outdoor cinema this month — a proper screen, premium concessions, and blankets on the lawn. Vote for the film below, then show up at dusk.",
    previewTags: ['Evening', 'Outdoor', 'All Ages'],
    formData: { eventType: 'Movie Night', budget: '$2,500 \u2013 $5,000', attendance: '30 \u2013 60 residents', season: 'Summer', venue: 'Indoor & Outdoor', alcohol: 'No alcohol', demographic: 'Mixed ages, family-oriented', notes: 'Outdoor cinema on the lawn. Premium concessions. Blankets and lawn chairs provided. Film selected by resident poll. Start at dusk. Non-alcoholic only.' },
  },

  {
    id: 'poolside-family-social', label: 'Poolside Family Social',
    tagline: 'The pool is open. Bring everyone.',
    description: 'A daytime poolside gathering with family-friendly activities, food, and music.',
    category: 'family', atmosphere: 'family-focused',
    demographic: ['Mixed ages, family-oriented', 'Mixed demographic'],
    idealSeasons: ['Summer'], budgetTier: 'mid',
    tags: ['no-alcohol', 'outdoor', 'all-ages', 'poolside'],
    venue: 'Indoor & Outdoor', alcohol: 'No alcohol',
    staffingComplexity: 'moderate', operationalDifficulty: 3, setupTimeHours: 2,
    cleanupComplexity: 'moderate',
    vendorTypes: ['Food caterer (taco or slider bar)', 'Non-alcoholic beverage vendor', 'Certified lifeguard'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'Agua fresca and premium lemonade in glass dispensers. Real food over cheap hot dogs. Shade and comfortable seating for non-swimming adults.',
    residentExperienceNotes: 'Family residents have the highest loyalty when buildings demonstrate care for their children.',
    setupNotes: 'Confirm lifeguard certification before any pool use — non-negotiable. Food station 15 feet minimum from pool edge. Shade structures essential.',
    staffingNotes: '1 certified lifeguard (non-negotiable). 2 caterer staff. 1–2 building staff.',
    enhancements: ['Bring in local taco or food truck vendor', 'Add poolside DJ for 2-hour midday set', "Add kids' craft table"],
    flyerHeadline: 'The pool is open. Bring everyone.',
    emailIntro: "We're hosting a poolside social this month — food, lawn games, and a proper summer afternoon for the whole building. All ages welcome. Just show up.",
    previewTags: ['Daytime', 'Outdoor', 'All Ages'],
    formData: { eventType: 'Pool Party', budget: '$2,500 \u2013 $5,000', attendance: '50 \u2013 100 residents', season: 'Summer', venue: 'Indoor & Outdoor', alcohol: 'No alcohol', demographic: 'Mixed ages, family-oriented', notes: 'All-ages poolside social. Lawn games, casual food spread (tacos, sliders), premium non-alcoholic drinks. Music at ambient level. Lifeguard required.' },
  },

  // ── SEASONAL ──────────────────────────────────────────────────────────────

  {
    id: 'grand-pool-opening', label: 'Grand Pool Opening',
    tagline: 'The pool is officially open. Summer starts now.',
    description: "The season's first rooftop pool activation — a proper debut with cocktails and music.",
    category: 'seasonal', atmosphere: 'upscale-social',
    demographic: ['Young professionals (25–35)', 'Mixed demographic'],
    idealSeasons: ['Summer'], budgetTier: 'premium',
    tags: ['full-bar', 'rooftop', 'poolside', 'debut'],
    venue: 'Indoor & Outdoor', alcohol: 'Full bar',
    staffingComplexity: 'intensive', operationalDifficulty: 4, setupTimeHours: 3,
    cleanupComplexity: 'involved',
    vendorTypes: ['Cocktail bar vendor', 'Poolside catering', 'DJ or music vendor', 'Event rental', 'Certified lifeguard'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'The opening toast is a signature moment — do not skip it. Poolside furniture quality matters. A signature summer cocktail with a building-specific name.',
    residentExperienceNotes: 'Residents anticipate this event from winter — it is a calendar anchor. High Instagram moment.',
    setupNotes: 'Lifeguard is non-negotiable. Bar requires rooftop load-in — confirm elevator access. Lounge chairs in clusters. Opening toast pre-poured and distributed.',
    staffingNotes: '2 bartenders minimum. 2 servers for passed bites. 1 certified lifeguard. 1 building event lead. 1 DJ.',
    enhancements: ['Commission signature summer cocktail named after building', 'Hire photographer for 2 hours', 'Add frozen rosé station'],
    flyerHeadline: 'The pool is officially open. Summer starts now.',
    emailIntro: "It's time. The rooftop pool is opening for the season and we're doing it properly — cocktails, music, and a champagne toast to mark the moment.",
    previewTags: ['Rooftop', 'Full Bar', 'Summer Debut'],
    formData: { eventType: 'Pool Party', budget: '$5,000 \u2013 $10,000', attendance: '50 \u2013 100 residents', season: 'Summer', venue: 'Indoor & Outdoor', alcohol: 'Full bar', demographic: 'Young professionals (25\u201335)', notes: 'Season opening event for the rooftop pool. Cocktail bar, DJ at ambient-to-social level, premium poolside catering. Resort casual. Champagne toast at opening.' },
  },

  {
    id: 'grand-winter-salon', label: 'Grand Winter Salon',
    tagline: 'The evening this building has been building toward all year.',
    description: "The building's signature end-of-year gathering — elegant, warm, and genuinely worth attending.",
    category: 'seasonal', atmosphere: 'upscale-social',
    demographic: ['Mixed demographic', 'Young professionals (25–35)', 'Mature residents (50+)', 'Mixed ages, family-oriented'],
    idealSeasons: ['Winter'], budgetTier: 'luxury',
    tags: ['full-bar', 'live-music', 'champagne', 'annual'],
    venue: 'Indoor', alcohol: 'Full bar',
    staffingComplexity: 'intensive', operationalDifficulty: 5, setupTimeHours: 6,
    cleanupComplexity: 'involved',
    vendorTypes: ['Full bar vendor with champagne service', 'Catering (passed canapés + food station)', 'Live music', 'Event décor and florals vendor', 'Event rental'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'Champagne on arrival sets the tone immediately — non-negotiable at this tier. Real floral and greenery décor. Live jazz elevates every conversation.',
    residentExperienceNotes: 'This is the event that justifies the decision to live in this building. The annual nature creates anticipation.',
    setupNotes: 'Full vendor load-in requires a half-day window. Champagne on trays for arrival. Real greenery, candlelight — no tinsel. Food station separate from bar.',
    staffingNotes: '3+ bartenders for 100+ guests. 3–4 servers. 1 coat check attendant. 1 building event director. Live music.',
    enhancements: ['Commission custom holiday cocktail named for the building', 'Hire professional photographer for full-event coverage', 'Partner with luxury local brand for resident gift bag'],
    flyerHeadline: 'The evening this building has been building toward all year.',
    emailIntro: "Every year we close the season with something worth dressing for. This year, we're opening the space for an evening of champagne, live music, and the company of everyone who makes this building what it is.",
    previewTags: ['Evening', 'Full Bar', 'Annual'],
    formData: { eventType: 'Holiday Party', budget: '$10,000 \u2013 $25,000', attendance: '75 \u2013 150 residents', season: 'Winter', venue: 'Indoor', alcohol: 'Full bar', demographic: 'Mixed demographic', notes: 'Annual winter celebration. Elegant but not formal. Champagne on arrival. Passed canapés and proper food station. Live acoustic music or jazz. The event residents talk about in January.' },
  },

  {
    id: 'harvest-supper-series', label: 'Harvest Supper Series',
    tagline: 'Peak season. Long table. One autumn evening.',
    description: 'A multi-course autumn supper built around peak-season local ingredients and communal dining.',
    category: 'seasonal', atmosphere: 'relaxed-luxury',
    demographic: ['Mixed demographic', 'Mature residents (50+)', 'Young professionals (25–35)'],
    idealSeasons: ['Fall / Autumn'], budgetTier: 'premium',
    tags: ['wine-beer', 'communal', 'farm-to-table', 'seasonal'],
    venue: 'Indoor', alcohol: 'Wine & beer only',
    staffingComplexity: 'intensive', operationalDifficulty: 4, setupTimeHours: 3,
    cleanupComplexity: 'involved',
    vendorTypes: ['Farm-to-table chef or caterer', 'Natural wine and cider vendor', 'Décor and floral vendor'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'The sourcing story is inseparable from the luxury — name every farm. Natural wine and cider signals intentionality. Candlelight and natural materials are the entire aesthetic.',
    residentExperienceNotes: 'Positions the building as culturally aware and food-literate. Communal format forces conversations residents remember for months.',
    setupNotes: 'Long communal table — single table if possible. Natural linen, beeswax candles, seasonal botanicals. Menu printed on kraft paper. Farm credits on the menu.',
    staffingNotes: '1 chef with 1–2 kitchen assistants. 2 servers. 1 building event lead. Chef present and visible throughout.',
    enhancements: ['Invite sourcing farmer to attend first course', 'Add natural wine merchant as featured guest', 'Commission harvest menu printed on seed paper'],
    flyerHeadline: 'Peak season. Long table. One autumn evening.',
    emailIntro: "This month we're marking the season properly — a harvest supper at a long communal table, built entirely from peak fall ingredients sourced from named local farms.",
    previewTags: ['Evening', 'Wine & Beer', 'Seasonal'],
    formData: { eventType: 'Brunch Gathering', budget: '$5,000 \u2013 $10,000', attendance: '30 \u2013 60 residents', season: 'Fall / Autumn', venue: 'Indoor', alcohol: 'Wine & beer only', demographic: 'Mixed demographic', notes: 'Autumn harvest supper. Multi-course seated dinner with peak fall ingredients from named local farms. Natural wine and craft cider pairings. Long communal table. Chef introduces each course.' },
  },

  {
    id: 'new-year-champagne-social', label: 'New Year Champagne Social',
    tagline: 'Ring in the new year right here. Champagne at midnight.',
    description: "An elegant New Year's Eve pre-celebration for residents — champagne, canapés, and a midnight toast.",
    category: 'seasonal', atmosphere: 'upscale-social',
    demographic: ['Mixed demographic', 'Mature residents (50+)', 'Young professionals (25–35)'],
    idealSeasons: ['Winter'], budgetTier: 'premium',
    tags: ['full-bar', 'champagne', 'midnight-toast', 'annual'],
    venue: 'Indoor', alcohol: 'Full bar',
    staffingComplexity: 'moderate', operationalDifficulty: 3, setupTimeHours: 2,
    cleanupComplexity: 'moderate',
    vendorTypes: ['Champagne and full bar vendor', 'Canapé caterer', 'Acoustic musician or curated playlist'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'The midnight toast is the entire event — everything before it is the anticipation. Pre-poured coupes at 11:50 PM signals choreography and care.',
    residentExperienceNotes: "Residents who spend New Year's Eve in the building will feel proud of their decision.",
    setupNotes: 'Champagne on trays ready at entrance for arrival. Midnight toast coupes pre-poured at 11:50 PM. Canapés passed continuously. Countdown clock visible.',
    staffingNotes: '2 bartenders. 2–3 servers for continuous canapé passing. 1 building event lead. 1 acoustic musician for first 2 hours.',
    enhancements: ['Feature prestige Champagne for midnight toast', 'Add photo booth for midnight countdown', 'Create custom "New Year\'s Eve Menu" card as keepsake'],
    flyerHeadline: 'Ring in the new year right here. Champagne at midnight.',
    emailIntro: "We're hosting New Year's Eve in the building this year — an elegant champagne social to close out the year with your neighbors. Champagne on arrival, canapés throughout, midnight toast.",
    previewTags: ['Evening', 'Full Bar', 'Midnight Toast'],
    formData: { eventType: 'Holiday Party', budget: '$5,000 \u2013 $10,000', attendance: '30 \u2013 60 residents', season: 'Winter', venue: 'Indoor', alcohol: 'Full bar', demographic: 'Mixed demographic', notes: "New Year's Eve champagne social. Champagne on arrival. Passed canapés throughout. Midnight toast with featured Champagne. No DJ — acoustic or curated playlist only." },
  },

  // ── EXPERIENTIAL / LUXURY POP-UP ──────────────────────────────────────────

  {
    id: 'the-champagne-residency', label: 'The Champagne Residency',
    tagline: 'Grower Champagnes. Caviar. Twenty-four seats.',
    description: 'A one-night champagne and sparkling wine experience led by a Champagne specialist.',
    category: 'experiential', atmosphere: 'upscale-social',
    demographic: ['Mature residents (50+)', 'Young professionals (25–35)'],
    idealSeasons: ['Winter', 'Fall / Autumn'], budgetTier: 'premium',
    tags: ['full-bar', 'champagne', 'caviar', 'limited-seats'],
    venue: 'Indoor', alcohol: 'Full bar',
    staffingComplexity: 'moderate', operationalDifficulty: 3, setupTimeHours: 2,
    cleanupComplexity: 'moderate',
    vendorTypes: ['Champagne specialist or sommelier', 'Caviar and fine foods vendor', 'Fine wine importer'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: 'Grower Champagnes residents cannot source locally are the draw. Caviar service elevates this beyond any wine tasting. The specialist narrative is the content of the evening.',
    residentExperienceNotes: 'Residents leave with genuine knowledge about Champagne. The rarity of the bottles is a conversation topic beyond the evening.',
    setupNotes: 'Flute and coupe stems pre-set — two per person minimum. Champagne served at 47–50°F. Caviar service: mother-of-pearl spoons only. Room silent during tasting commentary.',
    staffingNotes: '1 Champagne specialist. 1 trained server. 1 building staff for arrivals.',
    enhancements: ['Source prestige cuvée (Krug, Salon) as centerpiece pour', 'Commission custom printed tasting booklet', 'Offer residents opportunity to order featured bottles'],
    flyerHeadline: 'Grower Champagnes. Caviar. Twenty-four seats.',
    emailIntro: "We've arranged something genuinely special — an evening with a Champagne specialist featuring grower expressions you won't find at retail, paired with caviar service. Twenty-four seats.",
    previewTags: ['Evening', 'Full Bar', 'Limited Seats'],
    formData: { eventType: 'Cocktail Reception', budget: '$5,000 \u2013 $10,000', attendance: '20 \u2013 40 residents', season: 'Winter', venue: 'Indoor', alcohol: 'Full bar', demographic: 'Mature residents (50+)', notes: 'Champagne and sparkling wine tasting led by a specialist. 5–6 expressions including grower Champagnes. Paired with caviar service, blinis, crème fraîche. Maximum 24 residents.' },
  },

  {
    id: 'signature-chef-debut', label: 'Signature Chef Debut',
    tagline: '[Chef Name] is cooking in the building. Thirty seats only.',
    description: 'A one-night residency featuring a guest chef from a recognized local restaurant.',
    category: 'experiential', atmosphere: 'upscale-social',
    demographic: ['Mature residents (50+)', 'Young professionals (25–35)', 'Mixed demographic'],
    idealSeasons: ['Fall / Autumn', 'Winter'], budgetTier: 'luxury',
    tags: ['full-bar', 'chef-led', 'limited-seats', 'signature'],
    venue: 'Indoor', alcohol: 'Full bar',
    staffingComplexity: 'intensive', operationalDifficulty: 5, setupTimeHours: 4,
    cleanupComplexity: 'involved',
    vendorTypes: ['Guest chef and kitchen team', 'Sommelier for wine pairings', 'Event rental'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: "The chef's name and restaurant recognition is the entire luxury signal — source carefully. A keepsake menu card signed by the chef creates a lasting artifact.",
    residentExperienceNotes: 'Residents experience their building as a venue worthy of serious culinary talent. The dinner becomes a story.',
    setupNotes: 'Chef requires site visit 48–72 hours before. Full kitchen equipment list reviewed in advance. Printed menus with chef name and course descriptions at each seat.',
    staffingNotes: '1 guest chef plus kitchen team (2–3 people). 1 sommelier. 1–2 front-of-house servers. 1 building event lead.',
    enhancements: ['Create annual "Chef in Residence" series with different chef each season', 'Add pre-dinner kitchen preview for 5 residents', 'Commission short video of chef preparing a course'],
    flyerHeadline: '[Chef Name] is cooking in the building. Thirty seats only.',
    emailIntro: "We're bringing [Chef Name] of [Restaurant] into the building for one evening — a five-course tasting menu cooked exclusively for residents, with wine pairings. Thirty seats.",
    previewTags: ['Evening', 'Full Bar', 'Limited Seats'],
    formData: { eventType: 'Cooking Class', budget: '$10,000 \u2013 $25,000', attendance: '20 \u2013 40 residents', season: 'Fall / Autumn', venue: 'Indoor', alcohol: 'Full bar', demographic: 'Mixed demographic', notes: 'Guest chef from recognized local restaurant cooks 5-course tasting menu exclusively for building residents. Chef introduces each course. Wine pairings by sommelier. 30 residents maximum.' },
  },

  {
    id: 'resident-art-opening', label: 'Resident Art Opening',
    tagline: 'The gallery is the building. The artist lives here.',
    description: 'A curated gallery opening featuring work by resident artists or a commissioned local artist.',
    category: 'experiential', atmosphere: 'relaxed-luxury',
    demographic: ['Mixed demographic', 'Young professionals (25–35)', 'Mature residents (50+)'],
    idealSeasons: ['Spring', 'Fall / Autumn'], budgetTier: 'mid',
    tags: ['wine-beer', 'cultural', 'low-staffing', 'community'],
    venue: 'Indoor', alcohol: 'Wine & beer only',
    staffingComplexity: 'light', operationalDifficulty: 1, setupTimeHours: 2,
    cleanupComplexity: 'minimal',
    vendorTypes: ['Artist (resident or commissioned local)', 'Art hanging and installation vendor', 'Wine and beer vendor'],
    requiresExternalVendor: true,
    luxuryPresentationNotes: "Gallery-quality installation is the entire difference between this and a craft fair. The artist's presence transforms it from a display into an event.",
    residentExperienceNotes: 'Discovering a talented artist lives in the building creates genuine pride. The art remaining on display means every resident sees it.',
    setupNotes: 'Professional picture hanging with proper gallery hardware. Track lighting or spotlights on each piece. Work labels: title, medium, dimensions, artist name — printed and framed.',
    staffingNotes: 'The artist is the primary host. 1 building staff for wine management and coordination.',
    enhancements: ['Commission site-specific piece for lobby as permanent installation', 'Partner with local gallery to co-present the opening', 'Create printed exhibition catalogue as take-home'],
    flyerHeadline: 'The gallery is the building. The artist lives here.',
    emailIntro: "This month we're opening a gallery — right here in the building. Works by [Artist Name], a resident whose work deserves a proper showing. Wine, conversation, and the artist present all evening.",
    previewTags: ['Evening', 'Wine & Beer', 'Cultural'],
    formData: { eventType: 'Cocktail Reception', budget: '$2,500 \u2013 $5,000', attendance: '30 \u2013 60 residents', season: 'Spring', venue: 'Indoor', alcohol: 'Wine & beer only', demographic: 'Mixed demographic', notes: 'Gallery-style opening reception featuring a resident artist or commissioned local artist. Works displayed in lobby, hallways, or amenity space. Artist present. Wine and light bites.' },
  },

"""

# Find insertion point — before the closing section comment and ]
insert_marker = '  // ══════════════════════════════════════════════════════════════════════════\n]'

if insert_marker not in content:
    print("ERROR: Could not find insertion marker")
    print("Last 200 chars:", repr(content[-200:]))
    sys.exit(1)

# Insert before the closing marker
new_content = content.replace(insert_marker, new_templates + insert_marker, 1)

with open(templates_file, 'w') as f:
    f.write(new_content)

print(f"Done — inserted 30 templates into {templates_file}")
